-- Separate the on-chain owner from the Gramsrv profile hosting a collectible.
-- @relayer hosts a freshly exported NFT; @claim proves the current TON owner
-- and moves host_id to that owner's Gramsrv profile.

INSERT INTO public.users (
    id, access_hash, phone, first_name, last_name, username, country_code,
    created_at, updated_at, verified, support, about, last_seen_at,
    default_history_ttl_period, is_bot, bot_info_version, premium_expires_at,
    emoji_status_document_id, emoji_status_until, color_set, color,
    color_background_emoji_id, profile_color_set, profile_color,
    profile_color_background_emoji_id
) VALUES
(
    1250000019, 6184953271048627319, '', 'InvGram Gift Relayer', '', 'relayer', '',
    now(), now(), true, false,
    'On-chain InvGram Gifts waiting to be attached to their current owner profile.',
    0, 0, false, 0, NULL, 0, 0, false, 0, 0, false, 0, 0
),
(
    1250000021, 8462917350861429053, '', 'InvGram Gift Claim', '', 'claim', '',
    now(), now(), true, false,
    'Verify TON ownership and attach an InvGram Gift NFT to your profile.',
    0, 0, true, 1, NULL, 0, 0, false, 0, 0, false, 0, 0
)
ON CONFLICT (id) DO UPDATE SET
    access_hash=EXCLUDED.access_hash, first_name=EXCLUDED.first_name,
    username=EXCLUDED.username, verified=EXCLUDED.verified,
    about=EXCLUDED.about, is_bot=EXCLUDED.is_bot,
    bot_info_version=GREATEST(public.users.bot_info_version, EXCLUDED.bot_info_version),
    updated_at=now();

INSERT INTO public.bots (
    bot_user_id, owner_user_id, token_secret, description, commands,
    bot_chat_history, bot_nochats, inline_placeholder, created_at, updated_at,
    menu_button_type, menu_button_text, menu_button_url, bot_inline_geo
) VALUES (
    1250000021, 1250000021, '',
    'Prove current TON ownership and attach an InvGram Gift NFT to your Gramsrv profile.',
    '[{"command":"start","description":"open gift claim"}]'::jsonb,
    false, true, '', now(), now(), 0, '', '', false
)
ON CONFLICT (bot_user_id) DO UPDATE SET
    owner_user_id=EXCLUDED.owner_user_id, description=EXCLUDED.description,
    commands=EXCLUDED.commands, bot_chat_history=EXCLUDED.bot_chat_history,
    bot_nochats=EXCLUDED.bot_nochats, updated_at=now();

INSERT INTO public.peer_usernames
    (username_lower, username, peer_type, peer_id, active, editable, sort_order, updated_at)
VALUES
    ('relayer', 'relayer', 'user', 1250000019, true, false, 0, now()),
    ('claim', 'claim', 'user', 1250000021, true, false, 0, now())
ON CONFLICT (username_lower) DO UPDATE SET
    username=EXCLUDED.username, peer_type=EXCLUDED.peer_type, peer_id=EXCLUDED.peer_id,
    active=EXCLUDED.active, editable=EXCLUDED.editable, updated_at=now();

INSERT INTO public.read_model_versions (model, owner_user_id, peer_type, peer_id, version, updated_at, hash)
VALUES
    ('contact_account', 1250000019, 'user', 1250000019, 1, now(), 2500001900001),
    ('channel_active_memberships', 1250000019, 'user', 1250000019, 1, now(), 2500001900002),
    ('contact_account', 1250000021, 'user', 1250000021, 1, now(), 2500002100001),
    ('channel_active_memberships', 1250000021, 'user', 1250000021, 1, now(), 2500002100002)
ON CONFLICT (model, owner_user_id, peer_type, peer_id) DO UPDATE SET
    version=GREATEST(public.read_model_versions.version, EXCLUDED.version),
    updated_at=now(), hash=EXCLUDED.hash;

CREATE TABLE public.star_gift_claim_challenges (
    payload text PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    unique_gift_id bigint NOT NULL REFERENCES public.unique_star_gifts(id) ON DELETE CASCADE,
    expires_at integer NOT NULL,
    consumed_at integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT star_gift_claim_payload_check CHECK (payload ~ '^[0-9a-f]{64}$'),
    CONSTRAINT star_gift_claim_expiry_check CHECK (expires_at > 0),
    CONSTRAINT star_gift_claim_consumed_check CHECK (consumed_at IS NULL OR consumed_at > 0)
);
CREATE INDEX star_gift_claim_challenges_expiry_idx
    ON public.star_gift_claim_challenges(expires_at) WHERE consumed_at IS NULL;

CREATE TABLE public.star_gift_claim_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unique_gift_id bigint NOT NULL REFERENCES public.unique_star_gifts(id) ON DELETE RESTRICT,
    profile_user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
    wallet_address text NOT NULL,
    previous_wallet_address text NOT NULL,
    gift_address text NOT NULL,
    claimed_at integer NOT NULL,
    challenge_payload text NOT NULL UNIQUE,
    CONSTRAINT star_gift_claim_history_address_check CHECK (
        wallet_address <> '' AND gift_address <> '' AND claimed_at > 0
    )
);
CREATE INDEX star_gift_claim_history_gift_idx
    ON public.star_gift_claim_history(unique_gift_id, claimed_at DESC);

-- Backfill already exported gifts (including deployments upgraded in place).
UPDATE public.unique_star_gifts
SET host_peer_type='user', host_peer_id=1250000019, updated_at=now()
WHERE owner_address<>'' AND gift_address<>'' AND NOT burned
  AND (host_peer_type IS NULL OR host_peer_id IS NULL);

