-- Local, creator-claimed channel revenue withdrawals. The public confirmation
-- URL is a bearer capability; only its SHA-256 digest is persisted.
CREATE TABLE public.channel_revenue_withdrawals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_digest bytea NOT NULL,
    channel_id bigint NOT NULL,
    creator_user_id bigint NOT NULL,
    currency text NOT NULL,
    amount bigint NOT NULL,
    status text DEFAULT 'pending' NOT NULL,
    expires_at integer NOT NULL,
    created_at integer NOT NULL,
    completed_at integer,
    channel_transaction_id bigint,
    user_transaction_id bigint,
    channel_balance_after bigint,
    user_balance_after bigint,
    CONSTRAINT channel_revenue_withdrawals_token_unique UNIQUE (token_digest),
    CONSTRAINT channel_revenue_withdrawals_shape_check CHECK (
        octet_length(token_digest) = 32 AND
        channel_id > 0 AND creator_user_id > 0 AND amount > 0 AND
        currency IN ('stars', 'ton') AND status IN ('pending', 'completed') AND
        expires_at > created_at AND
        ((status = 'pending' AND completed_at IS NULL AND
          channel_transaction_id IS NULL AND user_transaction_id IS NULL AND
          channel_balance_after IS NULL AND user_balance_after IS NULL) OR
         (status = 'completed' AND completed_at IS NOT NULL AND completed_at >= created_at AND
          channel_transaction_id IS NOT NULL AND user_transaction_id IS NOT NULL AND
          channel_balance_after IS NOT NULL AND channel_balance_after >= 0 AND
          user_balance_after IS NOT NULL AND user_balance_after >= 0))
    )
);

CREATE INDEX channel_revenue_withdrawals_channel_idx
    ON public.channel_revenue_withdrawals(channel_id, id DESC);
CREATE UNIQUE INDEX channel_revenue_withdrawals_one_pending_currency_idx
    ON public.channel_revenue_withdrawals(channel_id, currency)
    WHERE status = 'pending';
CREATE INDEX channel_revenue_withdrawals_pending_expiry_idx
    ON public.channel_revenue_withdrawals(expires_at)
    WHERE status = 'pending';
